pingpong/dashboard/urls.py
from django.conf.urls import patterns as urls_patterns, url

from . import views

patterns = lambda *urls: urls_patterns('', *urls)

urlpatterns = patterns(
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^match/(?P<match_id>\d+)/score/set/$', views.set_score, name='set_score'),
    url(r'^match/(?P<match_id>\d+)/table/clear/$', views.clear_table, name='clear_table'),
    url(r'^match/(?P<match_id>\d+)/table/set/$', views.set_table, name='set_table'),
    url(r'^group/(?P<group_id>\d+)/score/set/$', views.set_group_scores, name='set_group_scores'),
    url(r'^match/history/$', views.match_history, name="match_history"),

    url(r'^match/upcoming/$', views.upcoming_matches),

    url(r'^match/(?P<match_id>\d+)/details/$', views.match_details),
    url(r'^tables/$', views.tables),
)

pingpong/signup/urls.py
from django.conf.urls import patterns as urls_patterns, url, include

from . import views

patterns = lambda *urls: urls_patterns('', *urls)

urlpatterns = patterns(
    url(r'^$', views.category_list, name='category_list'),
    url(r'^add/$', views.add_category, name='category_add'),
    url(r'^(?P<category_id>\d+)/', include(patterns(
        url(r'^$', views.category_details, name='category'),
        url(r'^edit/$', views.edit_category, name='edit_category'),
        url(r'^delete/$', views.delete_category, name='category_delete'),
        url(r'^print/$', views.print_category, name='category_print'),

        url(r'^brackets/create/$', views.create_brackets, name='create_brackets'),
        url(r'^brackets/delete/$', views.delete_brackets, name='delete_brackets'),

        url(r'^groups/create/$', views.create_groups, name='create_groups'),
        url(r'^groups/create_ng/$', views.create_groups_ng, name='create_groups_ng'),
        url(r'^groups/delete/', views.delete_groups, name='delete_groups'),

        url(r'^players.json$', views.category_players, name='category_players'),
        url(r'^players/edit/$', views.edit_category_players, name='category_edit_players'),
    ))),
    url(r'^known_clubs/$', views.known_clubs, name="known_clubs"),
    url(r'^known_players/$', views.known_players, name="known_players")
)

pingpong/urls.py
from django.conf.urls import patterns, include, url

from django.contrib.auth.views import login, logout

from django.contrib import admin
from . import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index),
    url(r'^category/', include('pingpong.signup.urls')),
    url(r'^dashboard/', include('pingpong.dashboard.urls')),

    url(r'^brackets_slideshow', 'pingpong.slideshow.views.brackets_slideshow', name='brackets_slideshow'),
    url(r'^groups_slideshow', 'pingpong.slideshow.views.groups_slideshow', name='groups_slideshow'),

    url(r'^accounts/login/$', login, name='auth_login', kwargs=dict(template_name='pingpong/login.html')),
    url(r'^accounts/logout/$', logout, name='auth_logout', kwargs=dict(template_name='pingpong/logged_out.html')),

    url(r'^report/$', 'pingpong.printing.views.print_report'),
    url(r'^results/$', 'pingpong.printing.views.print_results'),

    url(r'^admin/', include(admin.site.urls)),
)

tournament/urls.py
from django.conf.urls import patterns, include, url

from .registration import urls as player_urls
from .competition import urls as competition_urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include(competition_urls)),
    #url(r'^registration/', include(player_urls)),
    #url(r'^competition/', include(competition_urls)),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

pingpong/dashboard/models.py
from django.db import models

# Create your models here.

tournament/group/models.py
from django.db import models, IntegrityError

from ..player import models as player_models


class Group(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(player_models.Category)

    def __unicode__(self):
        return '{} - {}'.format(self.category, self.name)


class GroupMember(models.Model):
    player = models.ForeignKey(player_models.Player)
    group = models.ForeignKey('Group', related_name='members')

    place = models.IntegerField(blank=True, null=True)
    leader = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        super(GroupMember, self).save(*args, **kwargs)

        self.add_to_bracket()

    def add_to_bracket(self):
        if self.place is None:
            return
        try:
            transition = GroupToBracketTransition.objects.get(group=self.group_id, place=self.place)
            Match.objects.create(bracket=transition.bracket, player=self.player)
        except (GroupToBracketTransition.DoesNotExist, IntegrityError):
            pass


class Bracket(models.Model):
    category = models.ForeignKey(player_models.Category)
    level = models.IntegerField()

    winner_goes_to = models.ForeignKey('Bracket', blank=True, null=True, related_name='+')
    winner_order = models.IntegerField(default=0)

    loser_goes_to = models.ForeignKey('Bracket', blank=True, null=True, related_name='+')
    loser_order = models.IntegerField(default=0)


class Match(models.Model):
    class Meta:
        unique_together = (('bracket', 'player'),)

    bracket = models.ForeignKey(Bracket)
    order = models.IntegerField(default=0)

    table = models.CharField(max_length=50, blank=True)
    player = models.ForeignKey(player_models.Player)
    score = models.IntegerField(null=True)


class GroupToBracketTransition(models.Model):
    class Meta:
        unique_together = (('group', 'place'),)

    group = models.ForeignKey(Group)
    place = models.IntegerField()

    bracket = models.ForeignKey(Bracket)
    order = models.IntegerField(default=0)


class SetScore(models.Model):
    match = models.ForeignKey(Match)

    set = models.IntegerField()
    score = models.IntegerField()

pingpong/dashboard/views.py
import json
from django.contrib.auth.decorators import login_required

from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods

from pingpong.dashboard.forms import SetScoreForm, SetTableForm, GroupScoresFormset
from pingpong.models import Match, Table, Group, GroupMember
from pingpong.printing.helpers import print_matches


def dashboard(request):
    return render(request, 'pingpong/dashboard/dashboard.html')


def match_history(request):
    return render(request, 'pingpong/dashboard/match_history.html')


@login_required
def set_score(request, match_id):
    match = get_object_or_404(Match, id=match_id)

    if request.method == 'POST':
        set_score_form = SetScoreForm(request.POST, instance=match)
        if set_score_form.is_valid():
            set_score_form.save()
            return redirect(reverse('dashboard'))

    if request.is_ajax():
        template = 'pingpong/snippets/set_score_form.html'
    else:
        template = 'pingpong/dashboard/set_score.html'
    return render(request, template, dict(
        match=match,
        form=SetScoreForm(instance=match),
    ))


@login_required
def set_table(request, match_id):
    match = get_object_or_404(Match, id=match_id)

    if request.method == "POST":
        form = SetTableForm(request.POST, instance=match)
        if form.is_valid():
            form.save()
            if match.group_id is None:
                print_matches(match)
            return redirect(reverse('dashboard'))

    if request.is_ajax():
        template = 'pingpong/dashboard/set_table_modal.html'
    else:
        template = 'pingpong/dashboard/set_table.html'
    return render(request, template, dict(
        match=match,
    ))


@login_required
@require_http_methods('POST')
def clear_table(request, match_id):
    match = get_object_or_404(Match, id=match_id)

    if not match.status == Match.PLAYING:
        raise ValidationError(
            "You can only clear table on matches that are currently playing.")

    if match.group_id is not None:
        Match.objects.filter(group=match.group_id).update(table=None,
                                                          status=Match.PENDING)

    match.table = None
    match.status = Match.READY
    match.save()

    return redirect(reverse('dashboard'))


def upcoming_matches(request):
    response_data = []
    response_data.extend([
        dict(id=match.id,
             type='Group',
             group=unicode(match.group))
        for match in Match.ready_group_matches()
    ])
    response_data.extend([
        dict(id=match.id,
             type='Bracket',
             player1=unicode(match.player1),
             player2=unicode(match.player2))
        for match in Match.ready_bracket_matches()
    ])
    response_data.extend([
        dict(id=match.id,
             type='Double',
             player1=unicode(match.player1),
             player2=unicode(match.player2))
        for match in Match.ready_doubles_matches()
    ])
    return HttpResponse(json.dumps(response_data),
                        content_type="application/json")


def tables(request):
    response_data = []
    for table in Table.objects.order_by('display_order'):
        match = table.current_matches()
        if match:
            match = match[0]
            response_data.append(dict(
                table_name=table.short_name,
                match_id=match.id,
                match=unicode(match),
            ))
        else:
            response_data.append(dict(table_name=table.short_name))

    return HttpResponse(json.dumps(response_data),
                        content_type="application/json")


def match_details(request, match_id):
    match = get_object_or_404(Match, id=match_id)

    response_data = dict(
        id=match.id,
        status=match.status
    )
    if match.group_id:
        response_data['group'] = unicode(match.group)
    else:
        response_data.update(dict(
            player1=unicode(match.player1),
            player2=unicode(match.player2),
        ))

    return HttpResponse(json.dumps(response_data),
                        content_type="application/json")


@login_required
def set_group_scores(request, group_id):
    group = get_object_or_404(Group, id=group_id)

    if request.method == 'POST':
        group_scores = GroupScoresFormset(request.POST)
        if group_scores.is_valid():
            group_scores.save()
            return redirect(reverse('dashboard'))
    else:
        group_scores = GroupScoresFormset(queryset=GroupMember.for_group(group))

    return render(request, 'pingpong/category/edit_group.html',
                  dict(group=group,
                       formset=group_scores))

pingpong/live/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404

from pingpong.live.forms import UpcomingMatchesFromset, CurrentMatchesFromset, SetScoreForm
from pingpong.models import Category, Match, Table


def current_matches(request):
    try:
        category = Category.objects.all()[:1].get()
    except Category.DoesNotExist:
        return redirect('category_add')

    current_matches = Match.current_matches()
    if request.method == 'POST':
        formset = CurrentMatchesFromset(request.POST)
        if formset.is_valid():
            formset.save()
            return redirect('current_matches')
    else:
        formset = CurrentMatchesFromset(queryset=current_matches)

    return render(request, 'current_matches.html', {
        'category': category,
        'matches': current_matches,
        'formset': formset,
    })


def upcoming_matches(request):
    try:
        category = Category.objects.all()[:1].get()
    except Category.DoesNotExist:
        return redirect('category_add')

    group_matches = Match.ready_group_matches()
    bracket_matches = Match.ready_bracket_matches()
    doubles_matches = Match.ready_doubles_matches()

    if request.method == 'POST':
        formset = UpcomingMatchesFromset(request.POST)
        if formset.is_valid():
            instances = formset.save()
            matches_to_print = [instance for instance in instances
                                if instance is not None and instance.group is None]

            if matches_to_print:
                from pingpong.printing.helpers import print_matches
                print_matches(matches_to_print)
            return redirect('upcoming_matches')
    else:
        formset = UpcomingMatchesFromset(queryset=bracket_matches | group_matches | doubles_matches)

    return render(request, 'upcoming_matches.html', {
        'category': category,
        'formset': formset,
        'group_matches': group_matches,
        'bracket_matches': bracket_matches,
        'doubles_matches': doubles_matches,
    })


def set_score(request, table_id):
    table = get_object_or_404(Table, id=table_id)
    matches = table.current_matches()

    if request.method == 'POST':
        set_score_form = SetScoreForm(request.POST, instance=matches.get())
        if set_score_form.is_valid():
            set_score_form.save()
            return redirect(reverse('upcoming_matches'))

    if request.is_ajax():
        template = 'pingpong/snippets/set_score_form.html'
    else:
        template = 'pingpong/dashboard/set_score.html'
    return render(request, template, dict(
        table=table,
        matches=matches,
    ))

pingpong/printing/views.py
# Create your views here.
from django.shortcuts import render
from pingpong.models import Category, Bracket


def print_report(request):
    categories = Category.objects.filter(type=Category.SINGLE)
    return render(request, 'print_report.html', dict(categories=categories))


def print_results(request):
    brackets = Bracket.objects.order_by('category', 'id')
    categories_without_groups = Category.objects.filter(bracket__isnull=True, group__isnull=False).distinct()
    return render(request, 'print_results.html', dict(brackets=brackets,
                                                      categories_without_groups=categories_without_groups))

pingpong/slideshow/views.py
from django.db.models import Max, Count
from django.shortcuts import render
import itertools
from pingpong.models import Category, Group, GroupMember, Bracket, BracketSlot


def brackets_slideshow(request):
    bracket_groups = [[], [], []]
    pages = [0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

    for i, category in enumerate(Category.objects.order_by('id')):
        new_brackets = list(Bracket.objects.filter(category=category).order_by('id').annotate(rounds=Max('bracketslot__level')))
        bracket_groups[pages[i]].extend(new_brackets)

    return render(request, 'brackets_slideshow.html', dict(bracket_groups=bracket_groups[2:]))

def groups_slideshow(request):
    males = Category.objects.filter(gender=0).annotate(player_count=Count('players'))

    male_members = {
        category: []
        for category in males
    }
    for member in GroupMember.objects \
                             .filter(group__category__in=males) \
                             .order_by('group__category', 'group', 'place', '-leader', 'player__surname') \
                             .prefetch_related('group', 'group__category', 'player'):
        male_members[member.group.category].append(member)

    females = Category.objects.filter(gender=1).annotate(player_count=Count('players'))
    female_members = {
        category: []
        for category in females
    }
    for member in GroupMember.objects \
        .filter(group__category__in=females) \
        .order_by('group__category', 'group', 'place', '-leader', 'player__surname') \
        .prefetch_related('group', 'group__category', 'player'):
        female_members[member.group.category].append(member)

    groups = Group.objects.select_related('category')

    single_matches = BracketSlot.objects.filter(status=1, bracket__category__gender__lt=2) \
        .select_related('player', 'bracket__category')
    single_matches = [(a, list(b)) for a, b in itertools.groupby(single_matches, lambda x: x.winner_goes_to_id)]
    single_matches = [(match, slots) for match, slots in single_matches if len(slots) == 2]

    pair_matches = BracketSlot.objects.filter(status=1, bracket__category__gender__gte=2) \
        .select_related('player', 'bracket__category')
    pair_matches = [(a, list(b)) for a, b in itertools.groupby(pair_matches, lambda x: x.winner_goes_to_id)]
    pair_matches = [(match, slots) for match, slots in pair_matches if len(slots) == 2]

    return render(request, 'groups_slideshow.html', {
        'males': male_members.items(),
        'females': female_members.items(),
        'groups': groups,
        'single_matches': single_matches,
        'pair_matches': pair_matches,
    })

pingpong/signup/templates/pingpong/category_add.html
{% extends 'pingpong/category_base.html' %}
{% load i18n %}

{% block dropdown_menu %}{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">{% trans 'Add category' %}</h4>
        </div>
        <div class="panel-body">
            <table>
                {{ form }}
            </table>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-primary" value="Dodaj"/>
        </div>
    </div>
{% endblock %}

pingpong/signup/templates/pingpong/category_delete.html
{% extends 'pingpong/base_signup.html' %}
{% load i18n %}
{% load pingpong %}

{% block navigation %}{% endblock %}
{% block navigation_items %}{% endblock %}

{% block content %}
    <div>
        <p>
        {% blocktrans with category_name=category.name category_description=category.description %}
            Do you really want to delete category {{ category_description }} ({{ category_name }})?{% endblocktrans %}
        </p>
        <p>
           {% blocktrans %}The following objects will be deleted:{% endblocktrans %}
        </p>
            {% regroup related_objects by 0 as related %}
            {% for category in related %}
                <p>
                    <b>{{ category.grouper | capfirst }}</b>
                    {% for item in category.list %}
                        {{ item.1 }}{% if not forloop.last %},{% endif %}
                    {% endfor %}
                </p>
            {% endfor %}
        <div class="btn-group">
            <input type="submit" name="yes" class="btn btn-danger" value="{% trans 'Yes' %}"/>
            <input type="submit" name="no" class="btn btn-default" value="{% trans 'No' %}"/>
        </div>
    </div>
{% endblock %}

pingpong/signup/templates/pingpong/category_edit.html
{% extends 'pingpong/category_base.html' %}
{% load staticfiles %}
{% load categories %}

{% block javascript %}
    {% if category.type == category.SINGLE %}
        <script src="{% static 'js/jquery-ui-1.10.3.custom.min.js' %}"></script>
        <script>
            $(function () {
                var known_players = [
                    {name: "Jože", surname: "Hafner"},
                    {name: "Bojan", surname: "Vidmar"},
                    {name: "Jana", surname: "Drašler"},
                    {name: "Zdenko", surname: "Petrovič"},
                    {name: "Jože", surname: "Pogačar"},
                    {name: "Domen", surname: "Prijatelj"},
                    {name: "Bojan", surname: "Kuhelj"},
                    {name: "Miran", surname: "Merc"},
                    {name: "Boris", surname: "Škoberne"},
                    {name: "Marjan", surname: "Prijatelj"},
                    {name: "Franc Branko", surname: "Vidmar"},
                    {name: "Marjan", surname: "Šurca"},
                    {name: "Janez", surname: "Košir"},
                    {name: "Aleš", surname: "Smrekar"},
                    {name: "Bojan", surname: "Rauh"},
                    {name: "Matevž", surname: "Žgank"},
                    {name: "Bojan", surname: "Vokal"},
                    {name: "Iztok", surname: "Nadoh"},
                    {name: "Rado", surname: "Selan"},
                    {name: "Igor", surname: "Žgur"},
                    {name: "Nejc", surname: "Kovačič"},
                    {name: "Gregor", surname: "Svetec"},
                    {name: "Peter", surname: "Vrbančič"},
                    {name: "Franc", surname: "Strnišnik"},
                    {name: "Aleksander", surname: "Budič"},
                    {name: "Matic", surname: "Golavšek"},
                    {name: "Dragan", surname: "Živulovič"},
                    {name: "Iztok", surname: "Zupančič"},
                    {name: "Tone", surname: "Starc"},
                    {name: "Polde", surname: "Šuštar"},
                    {name: "Vojteh", surname: "Štor"},
                    {name: "Matjaž", surname: "Bavdek"},
                    {name: "Robert", surname: "Mali"},
                    {name: "Jernej", surname: "Lenko"},
                    {name: "Ciril", surname: "Omahen"},
                    {name: "Erih", surname: "Günther"},
                    {name: "Ljubo", surname: "Kovačič"},
                    {name: "Vinko", surname: "Pretnar"},
                    {name: "Franc", surname: "Žmavc"},
                    {name: "Damjan", surname: "Miklavčič"},
                    {name: "Tanja", surname: "Možek"},
                    {name: "Ciril", surname: "Kozjek"},
                    {name: "Jani", surname: "Lisac"},
                    {name: "Edo", surname: "Horvat"},
                    {name: "Marko", surname: "Bazovičar"},
                    {name: "Jaka", surname: "Bavdek"},
                    {name: "Primož", surname: "Prijatelj"},
                    {name: "Slobodan", surname: "Kukič"},
                    {name: "Nika", surname: "Možek"},
                    {name: "Iztok", surname: "Tuma"},
                    {name: "Matej", surname: "Cvetko"},
                    {name: "Dragica", surname: "Lapajne"},
                    {name: "Janez", surname: "Močan"},
                    {name: "Brane", surname: "Kralj"},
                    {name: "Luka", surname: "Mlakar"},
                    {name: "Stane", surname: "Glažar"},
                    {name: "Janez", surname: "Čekada"},
                    {name: "Tone", surname: "Meglen"},
                    {name: "Darko", surname: "Makovec"},
                    {name: "Jože", surname: "Miklavčič"},
                    {name: "Janez", surname: "Obštetar"},
                    {name: "Anja", surname: "Černe"},
                    {name: "Lojze", surname: "Zore"},
                    {name: "Janez", surname: "Erčulj"},
                    {name: "Gregor", surname: "Mlakar"},
                    {name: "Rastislav", surname: "Šuštaršič"},
                    {name: "Bojan", surname: "Supanič"},
                    {name: "Marjan", surname: "Zupančič"}
                ];
                var players = [];
                for (var i = 0; i < known_players.length; i++) {
                    players.push({label: known_players[i].name + ' ' + known_players[i].surname, value: known_players[i]});
                }

                var update_player = function (event, ui) {
                    event.preventDefault();
                    var form_number = $(this)[0].id.split('-')[1];
                    var $name = $("#id_player-" + form_number + "-name")[0];
                    var $surname = $("#id_player-" + form_number + "-surname")[0];

                    $name.value = ui.item.value.name;
                    $surname.value = ui.item.value.surname;
                }

                $(':text').autocomplete({
                    source: players,
                    delay: 0,
                    select: update_player,
                    focus: update_player
                });

                var form_number = $("#id_player-INITIAL_FORMS")[0].value;
                $("#id_player-" + form_number + "-name").focus();
            });
        </script>
    {% endif %}
{% endblock %}

{% block category_content %}
    {% edit_category_players category %}
{% endblock %}

pingpong/signup/templates/pingpong/confirm_deletion.html
{% extends 'pingpong/base_signup.html' %}
{% load i18n %}

{% block navigation %}{% endblock %}
{% block navigation_items %}{% endblock %}

{% block content %}
    <div>
        <p>
        {% blocktrans with category_name=category.name category_description=category.description %}
            Do you really want to delete {{ object_type }} {{ object_description }}?{% endblocktrans %}
        </p>
        <p>
           {% blocktrans %}The following related objects will be deleted:{% endblocktrans %}
        </p>
            {% regroup related_objects by 0 as related %}
            {% for category in related %}
                <p>
                    <b>{{ category.grouper | capfirst }}</b>
                    {% for item in category.list %}
                        {{ item.1 }}{% if not forloop.last %},{% endif %}
                    {% endfor %}
                </p>
            {% endfor %}
        <div class="btn-group">
            <input type="submit" name="yes" class="btn btn-danger" value="{% trans 'Yes' %}"/>
            <input type="submit" name="no" class="btn btn-default" value="{% trans 'No' %}"/>
        </div>
    </div>
{% endblock %}

pingpong/signup/templates/pingpong/edit_category.html
{% extends 'pingpong/base.html' %}

{% block content %}
    <form method="post" action="">
    {% csrf_token %}

    <div class="navbar navbar-fixed-top navbar-absolute">
        <div class="btn-group btn-group-lg">
        {% for c in categories %}
            <a href="{% url 'signup_category' id=c.id name=c.name %}" class="btn {% if c.id == category.id %}btn-primary{% else %}btn-default{% endif %}">{{ c }} ({{ c.player_count }})</a>
        {% endfor %}
        </div>
        <div class="btn-group btn-group-lg">
        <input type="submit" class="btn btn-primary disabled" value="Shrani" />
        </div>
    </div>
    <div style="margin-top:50px;">
        {{ formset.management_form }}
        {{ formset.non_form_errors.as_ul }}
        <table id="formset" class="form">
            {% for form in formset.forms %}
                {% if forloop.first %}
                    <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                            <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                {% endif %}
                <tr class="{% cycle row1,row2 %}">
                    {% for field in form.visible_fields %}
                        <td>
                            {# Include the hidden fields in the form #}
                            {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
    </form>
{% endblock %}